### ISSUE TITLE
Transfer combineRelay to CombineCommunity

### ISSUE THREAD

**Issue by dsk1306** [CombineCommunity/contributors#1]
Hi.
I’ve made a small [repo](https://github.com/dsk1306/combineRelay) with combine implementation of RxRelay and I’d like to ask if its possible to make it a part of Combine Community.
The repository has `combineCommunityMigration` branch with updated `LICENCE` and `README` files.

**Comment by dsk1306** [comment]
@freak4pc

**Comment by freak4pc** [comment]
Hey @dsk1306 - Sorry for the long time here and thanks for your awesome work! 
Can you please follow everything here and let me know once you have everything ready for transfer? Once you check off most of the items I'll add you as a member and than you can transfer it over yourself. Thanks! 

- [ ] replace copyright with "Copyright (c) Combine Community" in code
- [ ] replace copyright in README
- [ ] replace copyright in LICENSE
- [ ] Add `cocoapods@combine.community` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName cocoapods@combine.comomunity`.
- [ ] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings
- [ ] transfer repository ownership (once you're a contributor)
- [ ] fork the repo back to your personal account

**Comment by dsk1306** [comment]
Hi @freak4pc. Thank you for the answer.
I've double checked everything and it looks like the repo is ready for the transfer. How can I become a contributor (so I could transfer repository ownership)?

**Comment by freak4pc** [comment]
@dsk1306 I've invited you

**Comment by dsk1306** [comment]
@freak4pc thanks, I've transfer the repo's ownership to community.
