### ISSUE TITLE
CombineRealm

### ISSUE THREAD

**Issue by istvan-kreisz** [CombineCommunity/contributors#2]
As I mentioned on the slack channel, I'd like to transfer my [CombineRealm](https://github.com/istvan-kreisz/CombineRealm) repo over to the Combine community. The checklist is not yet completed but I'll get to it in the next few days.

- [x] replace copyright with "Copyright (c) Combine Community" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] Add `cocoapods@combine.community` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName cocoapods@combine.comomunity`.
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account

**Comment by istvan-kreisz** [comment]
Let me know if there are any additional steps I need to take other then the ones in the checklist

**Comment by istvan-kreisz** [comment]
hey @freak4pc I updated what I could but some points are still not clear:
- Running `pod trunk add-owner YourPodName cocoapods@combine.comomunity` yields "No owner found with the specified email address." I thought there was a typo in the email address so I tried with `cocoapods@combine.community` as well but same result 😕 
- do I also need to update the `author` and `homepage` fields in the Podspec?
- there's no CI setup rn, is that a hard requirement? I do plan on adding it, but when I tried I ran into some obscure errors so I just left it for now. I'll fix it for the next minor version upgrade though. Plus it has tests you just need to run `swift test` to see the result.
- I believe I'm not a contributor yet so I can't actually transfer the repo

I think that's all 😁 thanks!

**Comment by freak4pc** [comment]
Sorry @istvan-kreisz for the delay :) 

- There was an issue with the email, it should be fine to add an owner now - cocoapods@combine.community

- You don't have to remove yourself, but it would be good to add "Combine Community", "cocoapods@combine.community" as a second authorr

- CI isn't a hard requirement

- Let me know once you finish all the steps and I'll add you as a contributor to the organization

**Comment by istvan-kreisz** [comment]
Thanks @freak4pc 

So I added cocoapods@combine.community as pod owner and as a second author. 
I guess the only thing left is transferring the ownership (once that's done I'll also update the remote URL of the Podspec).

**Comment by freak4pc** [comment]
@istvan-kreisz I've sent you an invite :) Let me know if you need anything else and close this once you're done please.

Thanks !

**Comment by freak4pc** [comment]
Welcome to Combine Community 🥳🥳🥳
